### ISSUE TITLE
Buenos tests

### ISSUE THREAD

**Issue by semurat** [fermarja/t4_RemoteControlledShip_v1#1]
No se si hiciste el proyecto https://github.com/fermarja/t4_barco antes de que os pasara yo el codigo, jajajaja pero eso no quita para el comentario que he dejado en el issue https://github.com/fermarja/t4_barco/issues/1

En este los tests estan bien, probando todo lo que se pedia.

**Comment by fermarja** [comment]
Si, hice el otro primero, me pudo el nervio jajajaja

Gracias
